### ISSUE TITLE
Fehler im Setup beheben

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.cas#621]
**Beschreibung:**
Beim Versuch, Setup auf eine Datenbank auszuführen, treten viele Fehler auf:

- [ ] Vorher wurden die Tabellen mit `spring.jpa.hibernate.ddl-auto` erstellt, das Setup meckert dann: 
```
 Error while trying to execute procedure: setup: java.lang.RuntimeException: java.lang.RuntimeException: DropConstraint: Auf die PK__xtcasUse__F2954C2BAA174305-Einschränkung wird von der xtcasLuUserPrivilegeUserGroup-Tabelle, FOREIGN KEY-Einschränkung "FKsujjlmse6i5maken8u765hhgd" verwiesen.
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: DropConstraint: Auf die PK__xtcasUse__F2954C2BAA174305-Einschränkung wird von der xtcasLuUserPrivilegeUserGroup-Tabelle, FOREIGN KEY-Einschränkung "FKsujjlmse6i5maken8u765hhgd" verwiesen.
	at aero.minova.cas.setup.SetupService.lambda$setup$0(SetupService.java:81)
```
Man muss die entsprechenden Constraints und FKs manuell löschen, dann geht's weiter.

- [ ] es wird versucht, vorhandene Schlüssel ("setup") nochmal einzufügen
```
Procedure could not be executed: {? = call xpcasSetupInsertUserPrivilege(?,?,?)} ; Position: 2, Value: null ; Position: 3, Value: setup ; Position: 4, Value: null: Verletzung der UNIQUE KEY-Einschränkung "UK_xtcasUserPrivilege_KeyText". Ein doppelter Schlüssel kann in das dbo.xtcasUserPrivilege-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (setup).
com.microsoft.sqlserver.jdbc.SQLServerException: Verletzung der UNIQUE KEY-Einschränkung "UK_xtcasUserPrivilege_KeyText". Ein doppelter Schlüssel kann in das dbo.xtcasUserPrivilege-Objekt nicht eingefügt werden. Der doppelte Schlüsselwert ist (setup).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:518)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.execute(HikariProxyCallableStatement.java)
	at aero.minova.cas.service.ProcedureService.calculateSqlProcedureResult(ProcedureService.java:249)
```
Es sollte geprüft werden, ob der Eintrag schon vorhanden ist, statt einfach einzufügen und dann mit Fehler abzubrechen.

**Nachstellen:**
Schritte um das Verhalten/ den Fehler nachzustellen:

**Screenshots:**

**Betriebssystem:**

Abrechnung={XXX/XXX/XXX/ZWARTUNG}

**Comment by wis36** [comment]
Weiteres Problem:
Ich habe extra die Abhängigkeit von data.schema.app auf 12.10.3 erhöht,
und die neuen Dateien `min.workingtime-12.10.0-SNAPSHOT-app.jar` und `min.workingtime-12.10.0-SNAPSHOT.jar` in `lib` kopiert,
trotzdem bleibt beim Neustart & Setup die Version auf 12.5.8.

**Comment by martins-1992** [comment]
Der Fehler wird dadurch verursacht,
dass JPA und das Install-Tool gleichzeitig auf der Datenbank arbeiten.
Das geht aber nur schief.

* [ ] Table-XMLs nachreichen.
* [ ] Nach Absprache `spring.jpa.hibernate.ddl-auto=create` aus Doku entfernen und mit einer entsprechenden Warnung ersetzen.
  Es macht auch nicht viel Sinn, einige Tabellen mit JPA und einige mit Table-XML aufzusetzen.
  Da Table-XML erstmal nicht ersetzbar ist, muss es Table-XML sein.
