### ISSUE TITLE
CAS startet nicht mit fehlender Tabelle

### ISSUE THREAD

**Issue by wis36** [minova-afis/aero.minova.cas#649]
**Beschreibung:**
CAS startet nicht, anscheinend fehlt eine Tabelle, die es vorher noch nicht gab, die aber jetzt benötigt wird.

```
com.microsoft.sqlserver.jdbc.SQLServerException: Ungültiger Objektname "xtcasServiceMessageReceiverLoginType".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1676)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:540)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:459)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:239)
...
	at aero.minova.cas.servicenotifier.ServiceNotifierService.findOrCreateServiceMessageReceiverLoginType(ServiceNotifierService.java:139)
	at aero.minova.cas.servicenotifier.ServiceNotifierService.setup(ServiceNotifierService.java:69)
```

**Nachstellen:**
Schritte um das Verhalten/ den Fehler nachzustellen:

- Kopie von nicht ganz aktueller SIS-Datenbank
- CAS aufsetzen wie [hier](https://github.com/minova-afis/aero.minova.cas/blob/main/service/doc/adoc/installation.adoc#cas-als-windows-dienst-installieren) beschrieben
- CAS starten - es kommt die Fehlermeldung im Log und CAS beendet sich
- dadurch kann ich auch /setup nicht aufrufen, welches die fehlende Tabelle anlegen würde

**Betriebssystem:**
Windows

Abrechnung={XXX/XXX/XXX/ZWARTUNG}

**Comment by weber-minova** [comment]
Für das in der application.property ein: spring.jpa.hibernate.ddl-auto=update

**Comment by wis36** [comment]
Manche Tabellen sind NUR im JPA definiert, die anderen NUR in data.schema. Deswegen kommt es sich nicht mehr in die Quere.

Mit dem ddl-auto konnte ich den CAS jetzt starten.
