### ISSUE TITLE
Fehler beim CI

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#847]
**Beschreibung:**
Das Release läuft zwar durch, aber der CI bricht immer ab und wirft folgenden Fehler:
```
[INFO] cas.resource.maven.plugin .......................... SUCCESS [ 18.027 s]
[INFO] aero.minova.cas .................................... SUCCESS [ 15.860 s]
[INFO] aero.minova.cas.api ................................ SUCCESS [ 11.407 s]
[INFO] cas.service ........................................ SUCCESS [ 58.408 s]
[INFO] cas.extension.parent.internal ...................... FAILURE [  0.276 s]
[INFO] cas.app ............................................ SKIPPED
[INFO] cas.dev ............................................ SKIPPED
[INFO] core.application.system.app ........................ SKIPPED
[INFO] cas.extension.parent ............................... SKIPPED
[INFO] cas.extension.deployment ........................... SKIPPED
[INFO] cas-customer-build-project ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:52 min
[INFO] Finished at: 2023-12-27T14:41:43Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to parse plugin descriptor for aero.minova:cas.resource.maven.plugin:13.0.12-SNAPSHOT (/home/runner/work/aero.minova.cas/aero.minova.cas/resource-plugin/target/classes): No plugin descriptor found at META-INF/maven/plugin.xml -> [Help 1]
```

Das ist wirklich anstrengend beim Entwickeln und auch wegen des Dependabots, da man jedes Mal in den Logs schauen muss, ob es wegen desselben Fehlers abgebrochen ist oder wegen etwas anderem.

Abrechnung={XXX/XXX/XXX/ZWARTUNG}

**Comment by martins-1992** [comment]
Habe versucht den Fehler in dem CodeQL-Workflow zu fixen und habe danach den nächsten bekommen:
![grafik](https://github.com/minova-afis/aero.minova.cas/assets/7956931/70b0da27-ec7e-4326-9fcc-e069a7cb6b91)

Da wir SonarCube verwenden, würde ich den CodeQL-Workflow erstmal deaktivieren,
da es sonst nur zu Verwirrungen kommt und ich gerade keine Lösung finde.

**Comment by scholz-afis** [comment]
@weber-minova Ich glaube Du warst am falschen Problem dran: Ein paar Zeile weiter oben sagt `Environment.getProperty()`, dass es z.B. nicht die Umgebungsvariable `LIB` findet.
```
2024-01-26T08:38:57.9021515Z Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-01-26T08:38:57.9022909Z 2024-01-26T09:38:57.805 Application run failed
2024-01-26T08:38:57.9024826Z java.lang.IllegalArgumentException: Could not resolve placeholder 'LIB' in value "/opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so"
2024-01-26T08:38:57.9027183Z 	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)
2024-01-26T08:38:57.9029133Z 	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
2024-01-26T08:38:57.9031185Z 	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
2024-01-26T08:38:57.9033334Z 	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
2024-01-26T08:38:57.9035583Z 	at org.springframework.core.env.AbstractPropertyResolver.resolveNestedPlaceholders(AbstractPropertyResolver.java:230)
2024-01-26T08:38:57.9038265Z 	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:79)
2024-01-26T08:38:57.9041513Z 	at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:60)
2024-01-26T08:38:57.9043582Z 	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:552)
2024-01-26T08:38:57.9044899Z 	at aero.minova.cas.CustomLogger.lambda$handleContextRefresh$3(CustomLogger.java:129)
```

Dieses Symptom äußert sich, weil *CodeQL* eine nicht vorhandene Umgebungsvariable `LIB` in einer anderen Umgebungsvariable verwendet, aber das grundsätzliche Problem ist der Absturz der *CAS* Applikation aufgrund dieser Situation. Ich habe die Methode `.getProperty()` nun in einem `try` gekapselt, um das Problem als Warnung ausgeben zu können und die Applikation weiter laufen zu lassen: PR https://github.com/minova-afis/aero.minova.cas/pull/861

Cc: @martins-1992
